# Read up on pre-commit
# https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: check-merge-conflict
  - id: no-commit-to-branch
    args: [--branch, master]

- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: [
        -i,
        --wrap-summaries=88,
        --wrap-descriptions=88,
        --pre-summary-newline,
      ]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      additional_dependencies: [
        'pep8-naming',
        'flake8-comprehensions',
        'flake8-bugbear',
      ]
